version: 0.2
# imageUri: 416519539882.dkr.ecr.ap-southeast-1.amazonaws.com/peer-tutor-test
phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build -t peerTutor:latest .
      - docker tag <IMAGE_NAME> <ECR_URL>
  post_build:
    commands:
      - docker push <ECR_URL>
      - printf '[{"name":<TASK_DEFINITION_NAME>,"imageUri":"%s"}]' <ECR_URL> > imagedefinitions.json
artifacts:
  files: imagedefinitions.json